# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpvqxJC-N4pjRoXjWfqtm-HjOhM5HJmI
"""

fahrenheit = [[-67.0],[-34.0],[0.0],[34.0],[54.0],[67.0],[100.0]]
kelvins = [[218.15],[236.483],[255.372],[274.261],[285.372],[292.594],[310.928]]

import matplotlib.pyplot as plt


plt.figure(figsize=(15,8), dpi=50)
plt.scatter(fahrenheit, kelvins, label="Входные значения", color="green", marker="$f$");
plt.xlabel("fahrenheit")
plt.ylabel("kelvins")
plt.legend()
plt.grid(True)
plt.show()

for f, k in zip(fahrenheit, kelvins):
  print(f"фаренгейты{f} =кельвины{k}")

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(fahrenheit,kelvins)
lr.predict([[256],[123]])
lr.coef_
lr.intercept_
fahrenheit_test=[[-50],[10],[30],[20],[10],[70],[87]]
kelvins_test=lr.predict(fahrenheit_test)
kelvins_test

for f, k in zip(fahrenheit_test, kelvins_test):
  print(f"фаренгейты{f} =кельвины{k}")

import numpy as np
x_range=np.arange(-70,120)
y_range=(x_range+459.67)*5/9-273.2
plt.figure(figsize=(15,8), dpi=50)
plt.scatter(fahrenheit_test, kelvins_test, label="Входные значения", color="green", marker="$f$");
plt.xlabel("fahrenheit")
plt.ylabel("kelvins")
plt.legend()
plt.grid(True)
plt.show()

#1.2 GitHub
!git clone https://github.com/boheme7nocturne

#1 график
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(-5, 10, 0.1)
plt.plot(x,x**2)
plt.show()

#2 график
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(-5, 10, 0.1)
plt.plot(np.sin(x)**2)
plt.show()

#3 график
import matplotlib.pyplot as plt
import numpy as np

x=np.arange(-5, 10, 0.1)
plt.plot(x)
plt.plot(x**2)
plt.plot(x+1)
plt.plot(x*x)
plt.plot(2*x)
plt.plot(x+x**2)
plt.show()

#1.4 подключаем библиотеку math
import math
print("Число Эйлера е=",math.e)
print("Число Пи =",math.pi)
print("nan", math.nan)
print("Факториал числа 1 =",math.factorial(1))
print("Наибольший общий делитель=",math.gcd(6,128))