# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AAPn9iGle9rGYhFNN2SMlTs4Nrf49MJA
"""

print("Hello world")

a=5
b=2

c=a+b
print(c)

a=7.5
h=7.5
x=a/2*h
print(x)

a=5
b=2
c=-6
x=(a^2+b^2-c^3)/2
print(x)

"""uddhfjg;ioiiufytdy"""

a=5
b=int(input())
c=a*b
print(c)

a=int(input())
b=int(input())
c=(a+b)**2
print(c)

a=15
b=10
c=int(input())
v=(a+b)/c
print(v)

a=int(input())
b=int(input())
c=a**2+2*a*b+b**2
print(c)

v=a+b+c
n=(a+b)/2
a=int(input())
b=int(input())
c=int(input())
print(v)
print(n)

a=int(input())
b=int(input())
j=((a^3+14)/5)*b
print(j)

a=int(input())
n=int(input())
b=a**2
v=b//n
print(v)

a=float(input())
b=float(input())
c=int(input())
v=int(input())
m=a//b
k=c*v
h=c/v
print(m)
print(k)
print(h)

n=int(input())
d=((n//60)//60)//24
c=(n//60)//60
m=(n//60)
print(d)
print(c)
print(m)
g=n+n*n+n*n*n
print(g)