# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGt5IUlJrgMbmCdjaR-8yzYIcIr7Kzqf
"""

language = 'english'
if language == 'english':
    print ('Hello')
    print ('End')

language = 'russian'
if language == 'english':
    print ('Hello')
else:
    print('Привет')
print ('End')

language = 'german'
if language == 'english':
    print ('Hello')
    print ('World')
elif language == 'german':
    print ('Hallo')
    print ('Welt') 
else:
    print ('Привет')
    print ('Мир')

language = 'german'
if language == 'english':
    print ('Hello')
    print ('World')
elif language == 'russian':
    print ('Hallo')
    print ('Welt') 
else:
    print ('Привет')
    print ('Мир')

language = 'german'
if language == 'english':
    print ('Hello')
elif language == 'german':
    print ('Hallo')
elif language == 'french':
    print ('Salut')   
else:
    print ('Привет')

print ('Введите номер месяца:')

number = int(input())
if number == 1:
    print ('Январь')
elif number == 2:
    print ('Февраль')
elif number == 3:
    print ('Март')
elif number == 4:
    print ('Апрель')
elif number == 5:
    print ('Май')
elif number == 6:
    print ('Июнь')
elif number == 7:
    print ('Июль')
elif number == 8:
    print ('Август')
elif number == 9:
    print ('Сентябрь')        
elif number == 10:
    print ('Октябрь')
elif number == 11:
    print ('Ноябрь')
elif number == 12:
    print ('Декабрь')

print ('Введите число:')

x = int(input())
if x%2==0:
    print('Число чётное')
else:
    print('Число нечётное')

print ('Введите число:')

x = int(input())
if x>40:
    print('stonks')
else:
    print('not stonks')

def is_year_leap():
 print ('Введите год:')
 year = int(input())
 if year % 4 == 0 and (year%100!=0 or year%400==0):
  return True
 else:
  return False
is_year_leap()

def is_prime